### PR TITLE
Increase performance

### LINKED ISSUE #113: Unnecessary calls to validateForm kills performance
When a form is attached/mounted or detached/unmounted formsy calls validateForm not one time but many times for each component. This can be seen by debugging into the attachToForm or detachFromForm methods in main.js. 

This gives terrible performance when navigating from one big form to another. ValidateForm is then called first for every input component in the form you're navigating from and then for every component you're navigating to. For really big forms in Internet Explorer the app just freezes up with "long execution script error". 

It would seem that it should be sufficient to do this only one time in componentDidMount and componentWillUnmount. 
And maybe even consider a prop for those who dont need a initial validating when a form mounts/unmounts.

Monkeypatching like this solves the problem: 

```
Formsy.prototype.detachFromForm = function (component){
  const componentPos = this.inputs.indexOf(component);
  if (componentPos !== -1) {
    this.inputs = this.inputs.slice(0, componentPos).concat(this.inputs.slice(componentPos + 1));
  }
  NB!!! validateForm is commented out
   //this.validateForm();
};
```

### PR DESCRIPTION
**Pull request by golyakov**
fix #113

### CODE REVIEW

**Comment by amr** [comment]
This has fixed a performance issue I had with my form which had 100 fields. It's a dynamic tabular form, each row represents a contact (4 fields), and you add rows as needed, so with just 25 rows we get 100 fields.

Chrome debugger would kick in saying an out of memory crash is going to happen. This PR fixes that.

Thank you

**Comment by felixmosh** [comment]
Any updates on this pr?

**Comment by rkuykendall** [comment]
@golyakov  Thank you for this PR! I'd like to merge it immediately to master, which is now where the 2.0 branch is living now.

Unfortunately, it requires the branch to be cleaned up some. I realize it's been sitting stale for a long time, so if you have no more interest I can do it for you, but I'd prefer if it was your PR and not mine. Sorry for the trouble, I have a near-term goal of getting these build files out of PRs so they are easier to rebase and merge.

@golyakov @felixmosh @amr Additionally, if you're interested in working more on the project, I'll be watching the Gitter chat.

**Comment by golyakov** [comment]
@rkuykendall, I solved conflicts in PR

**Comment by rkuykendall** [comment]
@golyakov Thank you! Looks like 1 test is failing. The test relies on `componentWillReceiveProps` and I think it's not being called before the first assert because your new code is blocking it, as it's supposed to. Perhaps we should just default that value to true? or is there another lifecycle method we could use?

**Comment by rkuykendall** [comment]
@golyakov Verified locally that this would fix your failing test:

```diff
diff --git a/tests/Element-spec.js b/tests/Element-spec.js
index ad7a059..af5e264 100644
--- a/tests/Element-spec.js
+++ b/tests/Element-spec.js
@@ -171,6 +171,9 @@ export default {
 
     let isPristine = null;
     const Input = InputFactory({
+      componentDidMount: function() {
+        isPristine = this.props.isPristine;
+      },
       componentWillReceiveProps: function(nextProps) {
         isPristine = nextProps.isPristine;
       }
```

**Comment by golyakov** [comment]
@rkuykendall , thanks for the offer. I checked it and it did not work, because the number of component updates has now been reduced. I fixed the test. I believe that this test will be more correct. Please check the test.

**Pull request merged**
