### PR TITLE
1.1.1

### PR DESCRIPTION
**Pull request by rkuykendall**

### CODE REVIEW

**Comment by MilosRasic** [comment]
Is there a reason why you make PRs for your own changes and merge them yourself instead of just pushing to master? More importantly, should we always do it this way?

**Comment by rkuykendall** [comment]
@MilosRasic A few reasons, aside from the big one which is just habit: I never commit to master at work.

- I can easily review my diff before merging, make sure I didn't commit something by accident
- I know it passes tests
- There's no chance of a merge conflict because I pushed just a second after someone else pushed
- I don't have to to stash and pull and apply because someone else pushed or merged a commit while I was working, I can just rebase. Rebasing is really easy for me since I have it aliased:
```bash
alias rbm="git pull --rebase origin master"
```

Should we always? For features and anything that can be code reviewed I definitely think so. I'm a big fan of intense code review. As for version bumps + builds like this... clearly less necessary. I debated just going to master for this one, but I'm just prefer PRs.

**Comment by rkuykendall** [comment]
And yeah, this PR was one of the more ridiculous since there wasn't really anything to code review, so I just merged it as soon as it passed tests, but ¯\_(ツ)_/¯

**Comment by MilosRasic** [comment]
Thanks for the explanation. We usually do trunk-based development at work so this was a bit different. Trying to make sure I don't step on any toes by blatantly pushing to master when everyone else is making PRs :)

**Comment by rkuykendall** [comment]
Makes sense :) I'm curious, how do you avoid the issues I listed? Especially merging failing commits and updating your work to be in line with changes to the trunk as you're working.

**Comment by MilosRasic** [comment]
> I can easily review my diff before merging, make sure I didn't commit something by accident

I usually run git status and git diff if something looks suspicious for a bigger commit, but generally we try to stick to smaller commits so that you don't get a "why tf did I change this file?" moment.

> I know it passes tests

You can run tests manually locally or even better as a precommit hook.

> There's no chance of a merge conflict because I pushed just a second after someone else pushed

Merge conflicts aren't that scary. Also, if two commits would have had a merge conflict, and you put them each in their own branch and make a PR for each, wouldn't someone who is merging the PRs have to resolve the conflict anyway?

> I don't have to to stash and pull and apply because someone else pushed or merged a commit while I was working, I can just rebase. Rebasing is really easy for me since I have it aliased:

Same as above, not that scary, so I usually just pull, eat the merge conflicts and resolve them. It's actually a code review if you think about it because you have to check someone else's changes to merge them with your own :)

I agree about code reviews. We use jira with gitlab integration so our commits get linked to jira issues and we can review them from there, once they are already pushed to master. Since for formsy we use github for both git and issue tracking, handling code reviews throguh PRs make more sense.

https://www.gocd.org/2017/05/16/its-not-CI-its-CI-theatre.html probably explains what we do in as few words as possible.

**Pull request merged**
