### PR TITLE
Improve form valid state

### PR DESCRIPTION
**Pull request by rubencosta**
This PR has the following changes all related with form `isValid` state:

* `updateInputsWithError` now takes a second argument that when it evaluates to `true` causes the form to be invalidated
* passing non empty `validationErrors` causes the form to be invalidated unless `preventExternalInvalidation` is set
* updated API.md for `updateInputsWithError`

I have made this changes because I consider the form to be invalid when the fields have validation errors. I also depend on the form valid state for disabling the submit button while the form is invalid. This is inconsistent due to the submit button being disabled by client side validation but not by server side validation.

Thanks for this amazing library and all the hard work :)

### CODE REVIEW

**Comment by MilosRasic** [comment]
Looks good. Would you mind adding tests to cover this behavior?

**Comment by rkuykendall** [comment]
This looks really solid. Am I reading it right that this would invalidate the form in situations where it currently remains valid though?

**Comment by rubencosta** [comment]
@rkuykendall yes, passing a non empty `validationErrors` prop invalidates the form.

**Comment by rkuykendall** [comment]
@rubencosta Thank you for this PR as well! I'd like to merge it immediately to master.

Same as I said in the other PR, unfortunately, it requires the branch to be cleaned up some. I have a near-term goal of getting these build files out of PRs so they are easier to rebase and merge.

I'll be watching the Gitter chat. I would appreciate your expertise on this project if you're interested.

**Comment by rubencosta** [comment]
@rkuykendall I rebased the branch on the current master. I'm looking forward to seeing version 2 released :+1: 
I'll try and drop by the chat :)

**Pull request merged**
