### PR TITLE
Add function formsyRef.setValue to change only one input

### PR DESCRIPTION
**Pull request by ThibautMarechal**
# Add function to only change one input

It's like reset(), except it only modify one field.

https://github.com/formsy/formsy-react/issues/188

Let me know if i have to change anything.

### CODE REVIEW

**Comment by rkuykendall** [comment]
Hey @ThibautMarechal, thanks for the PR!

As you may notice, a lot has changed in the Formsy codebase recently. Sorry for the mess. But the good news is you can get rid of all these build files and not worry about your JS supporting IE6 since it's all compiled down.

As for this feature, I've been acquainting myself heavily with Formsy's build system but I've just now started learning the internals and I don't know enough about the API design to make significant changes to that on my own yet. Hopefully some others in the community can drop by and give their feedback. I know we've had similar issues like people wanting to set form model in a single function.

**Comment by ThibautMarechal** [comment]
I'm working on it to update my PR

**Comment by ThibautMarechal** [comment]
Review open 😉

**Comment by rkuykendall** [comment]
This looks very sensible to me, thank you for all the work! @twisty do you have any pro / con thoughts to this API addition? I want to be very careful with API changes as I've been mostly focusing on technical changes and API changes are hard to un-do.

@ThibautMarechal Could you drop the dist changes from the diff? They are no longer necessary in PRs since the build improvements to Formsy.

**Comment by ThibautMarechal** [comment]
Ok sorry about that. I will revert the dist folder :)

**Comment by ThibautMarechal** [comment]
@rkuykendall Your CI doesn't look like it build the package before testing it

**Comment by rkuykendall** [comment]
@ThibautMarechal You are very right, it definitely looks that way. I'm going to take a look at it right now because it definitely should be using the source.

**Comment by rkuykendall** [comment]
🎉 🎉 🎉

**Pull request merged**
