### PR TITLE
Bugfix: updateInputsWithValue doesn't update nested field

### PR DESCRIPTION
**Pull request by rkuykendall**
_( what is the feature, or what is it this is PR fixing? )_

- [x] Title is human readable, as it will be included directly in `CHANGELOG.md` when we do a release
- [x] If this is a new user-facing feature, documentation has been added to `API.md`
- [x] Any `dist/` changes have not been committed.

Tests run directly on the source code and all dist changes are computed and committed during Formsy release.

### CODE REVIEW

**Review by adsee42 — COMMENTED** [review]
Looks great👍 
Didn't know about lodash's `get` and `set`.😋

btw, (ignore this if I was wrong) this function looks and works very similarly to `updateInputsWithError`, and how they are implemented seems different. wondering why is the difference

**Comment by rkuykendall** [comment]
@adsee42 You're right. I thought a lot about this and I'm on the fence. Should you be able to pass object-style error messages like `{ foo: bar: 'Invalid phone number' }` map to the input `foo.bar`, or should, when setting error messages, you be required to supply the real name of the field?

The inputs with value one makes more sense, since we output an object at the end.

Of course none of this would matter except that `updateInputsWithError` throws an error if you supply a string that's not the name of the input, and that feature doesn't make sense if we support deep-error-objects, so we would want to remove it, which would be a "breaking" change, and therefore requires more thought.

**Comment by adsee42** [comment]
@rkuykendall 
I understand.
Though, why throwing errors if the names do not match? I suppose people using `updateInputsWithError` with their customized error object, and they would know if they didn't see the error messages supposed to show up?

**Comment by rkuykendall** [comment]
Yeah it feels like an odd feature. I guess the idea is that if you're passing errors to the form and they're not in the form, that's bad and we should let you know.

**Comment by rkuykendall** [comment]
I'm going to merge the change as-is and leave the questions about input errors for another conversation.

**Comment by rkuykendall** [comment]
@ThibautMarechal or @felixmosh Can I get a code review if you're free?

**Review by felixmosh — APPROVED** [review]
Looks OK to me :]

**Review by ThibautMarechal — APPROVED** [review]

**Pull request merged**
