### PR TITLE
Test for regex equality

### LINKED ISSUE #399: Infinite loop when comparing regular expressions
When `isSame` is called with a regular expression, they are tested using `a === b` comparison.

As regular expressions are passed by reference these are never equal and causes an infinite loop within `componentDidUpdate`.

### PR DESCRIPTION
**Pull request by mattmcdonald-uk**
Resolves #399

### CODE REVIEW

**Comment by rkuykendall** [comment]
*Thank you!* Do you mind waiting a bit for this to go out, at most a week? We just released 2.0.1 and if possible I'd like some more bugs and fixes to come in before we release 2.0.2 so as to not flood users with updates.

**Comment by mattmcdonald-uk** [comment]
No problem - I'm using my fork for the moment so isn't blocking me.

**Comment by twisty** [comment]
Super, thanks @mattmcdonald-uk! This one bit me this morning.

@rkuykendall Now it's in master I can use `formsy/formsy-react#master` in `package.json` so a little wait before 2.0.2 seems fine.

**Comment by rkuykendall** [comment]
@twisty If it's hitting you too, do you think a quick 2.0.2 is warranted? If it's widespread, the fix should be fast.

**Comment by twisty** [comment]
@rkuykendall Maybe a quick release of 2.0.2 would be best.

At the moment `/dist` on master isn't up-to-date with the source, so installing the master branch as a dependency doesn't include this fix.

**Comment by mattmcdonald-uk** [comment]
@twisty I created a separate branch for myself which includes it pre-built.

https://github.com/mattmcdonald-uk/formsy-react/tree/patch-built

**Comment by rkuykendall** [comment]
Yeah, this sounds serious and more pain than it's worth to wait. Published 2.0.2:

https://github.com/formsy/formsy-react/releases/tag/v2.0.2

**Pull request merged**
