### PR TITLE
Add cloneIfObject utility to reduce code duplication

### PR DESCRIPTION
**Pull request by rkuykendall**

### CODE REVIEW

**Comment by rkuykendall** [comment]
@felixmosh I had a little trouble understanding your previous PR, due to the original code being so messy. How does this look?

https://github.com/formsy/formsy-react/pull/337/files?utf8=%E2%9C%93&diff=unified&w=1

**Comment by felixmosh** [comment]
> @felixmosh I had a little trouble understanding your previous PR, due to the original code being so messy. How does this look?
> 
> https://github.com/formsy/formsy-react/pull/337/files?utf8=%E2%9C%93&diff=unified&w=1

what my previous PR? :]

**Comment by rkuykendall** [comment]
@felixmosh That was determined by someone other than I. I assume it needs copy of objects to prevent modification of internal data by external callees, and that if the same issue is present in arrays, then they also suffer the same problem. I'd love to use _.clone but that's not currently a dependency so that seems like a big decision.

**Comment by felixmosh** [comment]
Thanx for explanation, I think that in order to prevent future me from asking the same question, it is  better to add a test for this case :]

WDYT?

**Pull request merged**
